# DO NOT CHANGE config-version
config-version: 2

stat-bars:
  #
  # Formatting:
  # {profession}      - Profession name
  # {level}           - Profession level
  # {percentage}      - Percentage of level
  # {currentXp}       - Current XP count for level
  # {levelTotalXp}    - Total XP required for level
  format: "{profession} Lv.&b{level}&r {currentXp}&7/{levelTotalXp}"
  chatcolor-char: "&"
  mcmmo:
    enabled: true
  mmocore:
    enabled: true

  # Valid Colors:
  #  PINK,
  #  BLUE,
  #  RED,
  #  GREEN,
  #  YELLOW,
  #  PURPLE,
  #  WHITE;
  default-bar-color: YELLOW
  professions:
    acrobatics: PINK
    alchemy: PURPLE
    archery: BLUE
    axes: BLUE
    enchanting: PURPLE
    excavation: YELLOW
    farming: GREEN
    fishing: PURPLE
    herbalism: GREEN
    mining: YELLOW
    repair: PURPLE
    salvage: PURPLE
    smelting: PURPLE
    smithing: RED
    swords: BLUE
    taming: RED
    unarmed: BLUE
    woodcutting: GREEN